name: Continuous Deployment to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Use your preferred Node.js version
    - name: Install dependencies
      run: npm install
    - name: Build Vite project
      run: npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_access_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Vite's default build output folder
